version: '3'
services:
  mysql-db:
    container_name: flower-shop-mysql
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 3570951
      MYSQL_DATABASE: floricultura

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

