server:
  port: 8086
spring:
  redis:
    host: redis-db
    port: 6379
    password: p5Pagrt}FMaL9fkbqLN=u??Ctbs,hac-YAMAgBTm~Wpb%c=}y!9GzywxA*-)1>C}e}w9MXYE1ygtia-TgNt5F4P0FDNhW?WdXc}
  datasource:
    url: jdbc:mysql://mysql-db:3307/floricultura?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: xEgmJQ}3]@tgAU%bdb#K18fJAFUQ0KBf9]xEr_TNR}5gAB}ZN8eT]wa,0eUWURD5FAgqPzTiPL:bRCATrY+-rc%6nC)}G4Ejjq~K
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
api:
  security:
    token:
      secret: 9f1e3a222d4c6f8a7d5e6f81d4c6f8a71dab1c2e9d3f7a2e7b1cb1c2ee9d31d4c6f8a71df7a2e3f70c7b4c6f8a7b1c2a9d3f71d42e1de9
  link:
    address: http://localhost:8086
  java:
    mail:
      email: leia o readme !!
      password: leia o readme !!
