server:
  port: 8085
spring:
  redis:
    host: {seu ip aqui}
    port: 6379
    password: 224654
  datasource:
    url: jdbc:mysql://{seu ip aqui}:3307/floricultura?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 3570951
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
api:
  security:
    token:
      secret: 9f1e3a222d4c6f8a7d5e6f81d4c6f8a71dab1c2e9d3f7a2e7b1cb1c2ee9d31d4c6f8a71df7a2e3f70c7b4c6f8a7b1c2a9d3f71d42e1de9
  link:
    address: http://localhost:8085
  java:
    mail:
      email: leia o readme !!
      password: leia o readme !!
